[package]
name = "integer-reverse"
version = "0.1.0"
authors = ["kira-96 <847320916@QQ.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
